version: '3.9'
services:
  recipes-database:
    image: mongo
    ports:
      - '27017:27017'
  recipes-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://recipes-database:27017/recipes
    ports:
      - '3001:3001'
    depends_on:
      - recipes-database
  recipes-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: https://cuddly-space-lamp-5ggx96764ggp3ppvx-3001.app.github.dev/api/v1 # Use Codespaces URL or localhost:3001
    ports:
      - '3000:80'
    depends_on:
      - recipes-backend
